Repository 100-hours-a-week/20-real-cloud, pull requests merged in 2025-04, with the labels that each got.

#3 Update issue templates
  .github/ISSUE_TEMPLATE/✨-feature-template.md
  .github/ISSUE_TEMPLATE/🐞-bug-template.md
  .github/ISSUE_TEMPLATE/📋-docs-template.md
  .github/ISSUE_TEMPLATE/🔨-refactor-template.md
  .github/ISSUE_TEMPLATE/🚀--deploy-template.md
Labels: ⚙ Setting

#45 ✨ feat: Terrafrom Backend 구현
  .gitignore
  scripts/dummy.sh
  terraform/v1/backend/.terraform.lock.hcl
  terraform/v1/backend/main.tf
  terraform/v1/backend/outputs.tf
  terraform/v1/envs/mvp/.terraform.lock.hcl
  terraform/v1/envs/mvp/backend.tf
  terraform/v1/envs/mvp/main.tf
  terraform/v1/envs/mvp/provider.tf
  terraform/v1/envs/mvp/versions.tf
  terraform/v1/modules/dummy.md
  terraform/v2/dummy.md
Labels: ✨ Feature

#46 📝 docs: 테라폼 협업 가이드 Readme.md에 추가
  README.md
Labels: 📃 Docs

#47 📝 docs: README.md 수정
  README.md
Labels: 📃 Docs

#49 📝 docs: README 수정
  README.md
Labels: 📃 Docs
